### ISSUE TITLE
NAIP 2014 Southmost DOQQs missing

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#13]
NAIP 2014 Southmost DOQQs missing. We have data for NAIP 2012.

**Comment by wilsaj** [comment]
example?

**Comment by wilsaj** [comment]
Oh, I see. Quad name is Southmost, not the general direction :arrow_down:

**Comment by mitchellryant** [comment]
![pancakes](https://cloud.githubusercontent.com/assets/8459928/7614131/69152c7a-f95a-11e4-9dba-a9f993a6c0fe.gif)

**Comment by wilsaj** [comment]
Ok, looked into it. The new data organization scheme is based on quad number, since quad names are imprecise and not unique. The old data-download stuff was keyed off of name, though, so to do the migration we need a complete dataset that matches old quad names -> quad numbers. The quad number -> quad name translation that we are currently using is this: https://tnris.cartodb.com/tables/tnris_quad_wgs84_original

Southmost quad isn't in there, so it is getting skipped. Do you have a complete dataset of quads?

**Comment by mitchellryant** [comment]
this gives me a head everytime.

![blah](https://cloud.githubusercontent.com/assets/8459928/7615581/3b76267a-f964-11e4-8f5c-3cc553108ed2.PNG)

**Comment by wilsaj** [comment]
we good on these now?

**Comment by wilsaj** [comment]
done
