### ISSUE TITLE
No data returns for Port O'Connor

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#32]
No data returns for Port O'Connor or Port Oconnor.

Quad Number - QuadNum	2896_37

![portoconn0r](https://cloud.githubusercontent.com/assets/8459928/10105076/825d136e-6372-11e5-8774-873d68c6d4a4.PNG)

**Comment by jseppi** [comment]
The API requests (like `http://tnris.org/data-download/api/v1/areas?filter=type+%3D+%27quad%27+AND+name+LIKE+%27Port+O%27Connor%27&limit=300`) result 400 errors, due to the apostrophe (`%27`) in "O'Connor" improperly terminating the SQL queries.
Using quotation marks (`%22`) to wrap the name seems to work (ex `http://tnris.org/data-download/api/v1/areas?filter=type+%3D+%27quad%27+AND+name+LIKE+%22Port+O%27Connor%22&limit=300`)
